[buildPlans.IosevkaRootiestV2]
family = "Iosevka Rootiest v2"
spacing = "term"
serifs = "sans"
noCvSs = false
exportGlyphNames = true
buildTextureFeature = true

[buildPlans.IosevkaRootiestV2.variants.design]
one = "base-long-top-serif"
two = "curly-neck-serifed"
three = "flat-top-serifed"
four = "semi-open-serifed"
five = "oblique-flat-serifed"
six = "open-contour"
seven = "bend-serifed-crossbar"
eight = "two-circles"
nine = "open-contour"
zero = "long-dotted"
capital-a = "round-top-base-serifed"
capital-b = "more-asymmetric-interrupted-bilateral-serifed"
capital-c = "bilateral-serifed"
capital-d = "standard-bilateral-serifed"
capital-e = "serifed"
capital-f = "serifed"
capital-g = "toothless-rounded-serifed-capped"
capital-h = "serifed"
capital-i = "serifed"
capital-j = "descending-serifed-both-sides"
capital-k = "curly-serifed"
capital-l = "serifed"
capital-m = "hanging-serifed"
capital-n = "asymmetric-motion-serifed"
capital-p = "open-serifed"
capital-q = "detached-bend-tailed"
capital-r = "standing-open-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "motion-serifed"
capital-u = "toothless-rounded-serifed"
capital-v = "curly-serifed"
capital-w = "rounded-vertical-sides-serifed"
capital-x = "curly-bilateral-motion-serifed"
capital-y = "curly-serifed"
capital-z = "cursive-with-horizontal-crossbar"
a = "double-storey-tailed"
b = "toothed-serifed"
c = "bilateral-inward-serifed"
d = "tailed-serifless"
e = "rounded"
f = "tailed-crossbar-at-x-height"
g = "double-storey-open"
h = "tailed-motion-serifed"
i = "tailed-serifed"
j = "serifless"
k = "diagonal-tailed-cursive-top-left-serifed"
l = "tailed"
m = "earless-single-arch-short-leg-tailed-serifed"
n = "earless-rounded-straight-serifed"
p = "earless-rounded-serifed"
q = "earless-rounded-diagonal-tailed-serifless"
r = "top-serifed"
s = "serifless"
t = "bent-hook-asymmetric-short-neck"
u = "tailed-motion-serifed"
v = "cursive-serifed"
w = "rounded-vertical-sides-serifless"
x = "cursive"
y = "cursive-serifless"
z = "cursive"
long-s = "bent-hook-tailed"
eszet = "traditional-serifless"
lower-eth = "curly-bar"
capital-thorn = "serifed"
lower-thorn = "serifed"
capital-lambda = "curly-serifless"
lower-lambda = "curly-tailed-turn"
lower-chi = "chancery"
lower-psi = "serifless"
cyrl-a = "double-storey-hook-inward-serifed-tailed"
cyrl-ve = "standard-interrupted-serifless"
cyrl-capital-zhe = "cursive"
cyrl-zhe = "cursive"
cyrl-capital-ze = "bilateral-inward-serifed"
cyrl-ze = "bilateral-inward-serifed"
cyrl-capital-ka = "curly-serifless"
cyrl-ka = "curly-serifless"
cyrl-el = "tailed"
cyrl-em = "hanging-serifless"
cyrl-en = "tailed-serifless"
cyrl-capital-er = "open-serifless"
cyrl-er = "eared-serifless"
cyrl-capital-u = "curly-serifless"
cyrl-u = "curly-serifless"
cyrl-ef = "cursive"
cyrl-che = "tailed"
cyrl-yeri = "cursive"
cyrl-yery = "corner-tailed"
cyrl-capital-e = "bilateral-inward-serifed"
cyrl-e = "bilateral-inward-serifed"
cyrl-capital-ya = "curly-serifless"
cyrl-ya = "curly-open-tailed-serifless"
tilde = "high"
asterisk = "hex-mid"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "curly"
number-sign = "upright-open-tall"
ampersand = "lower-open"
at = "fourfold-solid-inner-tall"
dollar = "slanted-interrupted"
cent = "slanted-bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
question = "corner"
pilcrow = "low"
micro-sign = "toothless-corner-serifless"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted-dotted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaRootiestV2.variants.italic]
one = "base-long-top-serif"
two = "curly-neck-serifed"
three = "flat-top-serifed"
four = "semi-open-serifed"
five = "oblique-flat-serifed"
six = "open-contour"
seven = "bend-serifed-crossbar"
eight = "two-circles"
nine = "open-contour"
zero = "broken-slash"
capital-a = "round-top-serifless"
capital-b = "more-asymmetric-interrupted-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-h = "serifless"
capital-i = "short-serifed"
capital-j = "descending-serifless"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "slanted-sides-hanging-serifless"
capital-n = "asymmetric-serifless"
capital-p = "open-serifed"
capital-q = "open-swash"
capital-r = "standing-open-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "rounded-vertical-sides-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "cursive"
a = "double-storey-hook-inward-serifed-toothless-rounded"
b = "toothless-corner-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "flat-hook-tailed"
g = "double-storey"
h = "tailed-serifless"
i = "tailed"
j = "serifed"
k = "diagonal-tailed-cursive-serifless"
l = "tailed"
m = "earless-single-arch-short-leg-tailed-serifed"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-diagonal-tailed-serifless"
r = "earless-corner-serifless"
s = "serifless"
t = "bent-hook-asymmetric-short-neck2"
u = "toothless-rounded-serifless"
v = "cursive-serifless"
w = "rounded-vertical-sides-serifless"
x = "cursive"
y = "cursive-serifless"
z = "cursive-with-crossbar"
long-s = "bent-hook-tailed"
eszet = "traditional-serifless"
lower-eth = "curly-bar"
capital-delta = "curly"
lower-xi = "rounded"
cyrl-ef = "diagonal-tailed-cursive"
tilde = "high"
asterisk = "hex-mid"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "curly"
number-sign = "slanted-open-tall"
ampersand = "upper-open"
at = "fourfold-solid-inner-tall"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
question = "smooth"
pilcrow = "low"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted-dotted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaRootiestV2.variants.oblique]
one = "base-long-top-serif"
two = "curly-neck-serifed"
three = "flat-top-serifed"
four = "semi-open-serifed"
five = "oblique-flat-serifed"
six = "closed-contour"
seven = "bend-serifed-crossbar"
eight = "two-circles"
nine = "closed-contour"
zero = "broken-vertical-bar"
capital-a = "round-top-serifless"
capital-b = "more-asymmetric-interrupted-bilateral-serifed"
capital-c = "bilateral-serifed"
capital-d = "more-rounded-bilateral-serifed"
capital-e = "serifed-capped"
capital-f = "serifed-capped"
capital-g = "toothed-inward-serifed-capped"
capital-h = "serifed"
capital-i = "serifed"
capital-j = "descending-serifed-both-sides"
capital-k = "symmetric-connected-serifed"
capital-l = "serifed"
capital-m = "hanging-serifed"
capital-n = "asymmetric-serifed"
capital-p = "open-serifed"
capital-q = "vertical-crossing"
capital-r = "standing-open-serifed"
capital-s = "bilateral-inward-serifed"
capital-t = "serifed"
capital-u = "toothless-rounded-serifed"
capital-v = "curly-serifed"
capital-w = "rounded-vertical-sides-serifed"
capital-x = "curly-serifed"
capital-y = "curly-serifed"
capital-z = "cursive-with-crossbar"
a = "double-storey-serifless"
b = "toothed-serifed"
c = "bilateral-inward-serifed"
d = "tailed-serifed"
e = "rounded"
f = "tailed-crossbar-at-x-height"
g = "double-storey-open"
h = "tailed-serifed"
i = "tailed-serifed"
j = "serifless"
k = "diagonal-tailed-cursive-top-left-serifed"
l = "tailed"
m = "earless-single-arch-short-leg-tailed-serifed"
n = "earless-rounded-straight-serifed"
p = "earless-rounded-serifed"
q = "earless-rounded-diagonal-tailed-serifless"
r = "top-serifed"
s = "serifless"
t = "bent-hook-asymmetric-short-neck"
u = "tailed-motion-serifed"
v = "cursive-serifed"
w = "rounded-vertical-sides-serifless"
x = "cursive"
y = "cursive-flat-hook-serifless"
z = "cursive-with-horizontal-crossbar"
long-s = "bent-hook-tailed"
eszet = "traditional-serifless"
lower-eth = "curly-bar"
capital-delta = "curly"
lower-mu = "tailed-serifed"
lower-xi = "rounded"
tilde = "high"
asterisk = "hex-mid"
paren = "flat-arc"
brace = "curly-flat-boundary"
guillemet = "curly"
number-sign = "slanted-open-tall"
ampersand = "flat-top"
at = "threefold-solid-inner-tall"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
question = "corner-flat-hooked"
pilcrow = "low"
lig-ltgteq = "slanted"
lig-neq = "slightly-slanted-dotted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaRootiestV2.ligations]
inherits = "dlig"

[buildPlans.IosevkaRootiestV2.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.IosevkaRootiestV2.widths.Extended]
shape = 600
menu = 7
css = "expanded"

[buildPlans.IosevkaRootiestV2.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.IosevkaRootiestV2.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

[buildPlans.IosevkaRootiestV2.widths.SemiExtended]
shape = 548
menu = 6
css = "semi-expanded"

[buildPlans.IosevkaRootiestV2.widths.ExtraExtended]
shape = 658
menu = 8
css = "extra-expanded"

[buildPlans.IosevkaRootiestV2.widths.UltraExtended]
shape = 720
menu = 9
css = "ultra-expanded"
